title: "Test Site"
description: "A test site for Markdown guides"
baseurl: "/Test"
url: "https://lorensfs.github.io"
markdown: kramdown
theme: jekyll-theme-minimal
exclude:
  - "Guía simple para crear librería en Python.md"
permalink: pretty
