# Configuración del sitio
title: "Sitio de Documentación"
description: "Guías claras y legibles sobre Python y Markdown"
baseurl: "/Test" # Ajusta según tu repositorio
url: "https://lorensfs.github.io"
markdown: kramdown

# Tema minimalista para legibilidad
theme: jekyll-theme-minimal

# Plugins opcionales
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Excluir archivos que no deben mostrarse
exclude:
  - "Guía simple para crear librería en Python.md"

# Estructura de enlaces permanentes
permalink: pretty

# Añadir CSS personalizado para mejorar la legibilidad
custom_css: styles.css
