# Configuración del sitio
title: "Sitio de Documentación"
description: "Guías útiles sobre Python y Markdown"
baseurl: "/Test" # Ajusta a tu nombre de repositorio
url: "https://lorensfs.github.io"
markdown: kramdown

# Tema personalizado minimalista con soporte para dark mode
theme: jekyll-theme-minimal  # O jekyll-theme-cayman para algo más visual

# Plugins (opcional)
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Excluir archivos específicos
exclude:
  - "Guía simple para crear librería en Python.md"

# Permalinks
permalink: pretty

# Dark mode toggle support (simple implementation)
custom_css: styles.css

