# Configuración del sitio
title: "Sitio de Documentación"
description: "Guías útiles sobre Python y Markdown"
baseurl: "/Test" # Ajusta a tu nombre de repositorio
url: "https://lorensfs.github.io"
markdown: kramdown

# Tema para el diseño
theme: jekyll-theme-cayman  # O usa jekyll-theme-minimal si prefieres algo más sencillo

# Plugins para RSS y Sitemap (opcional)
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Excluir archivos markdown específicos
exclude:
  - "Guía simple para crear librería en Python.md"

# Estructura de permalinks para URLs limpias
permalink: pretty
